version: 1.0.{build}

image: Visual Studio 2022

environment:
  nodejs_version: "24"
  CI: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm ci

build_script:
  - npm run build

test_script:
  - npm test

artifacts:
  - path: dist
    name: socketlistenersample-build

cache:
  - '%APPDATA%\npm-cache -> package-lock.json'
  - node_modules -> package-lock.json
